### ISSUE TITLE
Add description of order in groups-ordering

### ISSUE THREAD

**Issue by gvNN7** [KyleMayes/eslint-plugin-ordered-imports#19] opened 2021-08-30 20:27 UTC
Hey Kyle, everything's fine? 

I'm have a question about the `order` param in `group-ordering`, what this number affect in the sort? It's something like bigger to smaller or vice-versa? The order in the array `group-ordering` affects anything? This is not clear to me in the documentation.

Can you give me a explain about this? 

I'm trying to achieve something like -> side-effect -> default -> destructured -> namespace

From this: 

```
import { Component } from '../../types'
import React from 'react'
import * as Foo from 'bar'
import { isEqual, isEmpty } from 'lodash'
import { useSelector } from 'react-redux'
import config from 'react-native-config'
import Url from 'url-parse'
```

to this: 

```
import React from 'react'
import config from 'react-native-config'
import Url from 'url-parse'

import { isEqual, isEmpty } from 'lodash'
import { useSelector } from 'react-redux'
import { Component } from '../../types'

import * as Foo from 'bar'
```

but i'm getting this: 

```
import * as Foo from 'bar'

import { isEqual, isEmpty } from 'lodash'
import { useSelector } from 'react-redux'
import { Component } from '../../types'

import React from 'react'
import config from 'react-native-config'
import Url from 'url-parse'
```

this is my .eslint.js file: 
```jsx
'ordered-imports/ordered-imports': [
      'warn',
      {
        'symbols-first': false,
        'declaration-ordering': [
          'type',
          {
            ordering: ['side-effect', 'default', 'destructured', 'namespace'],
            secondaryOrdering: ['any']
          }
        ],
        'specifier-ordering': 'any',
        'group-ordering': [
          { name: 'react and etc', match: '^react$|url', order: 10 },
          { name: 'packages', match: '^lodash|react', order: 20 },
          { name: 'constants', match: '^bar$', order: 5 },
        ],
      },
    ],
```

**Comment by KyleMayes** [comment] 2021-08-30 22:20
Hello,

The README could definitely be improved to better describe how imports are grouped and how those groups are then ordered.
I'll look into improvements there but to answer your first question about `"order"`:

Import statements are assigned to groups by iterating through the groups in the `group-ordering` and picking the first group with a `match` value that matches the import source (e.g., `'react'` in `import React from 'react';` would satisfy `"match": "^react"`).

Once all import statements are assigned to groups, the groups are then sorted in ascending order using the `"order"` value as the sort key.

The `"order"` field exists because there are times where you want to change the matching precedence of import groups without affecting the order of the import groups. For example the recommended configuration has a catch-all group with `"match": ".*"` which must appear last in the `"group-ordering"` block otherwise it would match every import statement. But because this import group should come first in the file, it is assigned the lowest `"order"` value of `5`.

As for what it looks like you are trying to accomplish (grouping imports by import type), that isn't a feature this plugin really supports. The import grouping feature was intended primarily for grouping imports by things like what directory they are from like in the recommended configuration.

You can continue to try emulating this feature by creating `"match"` patterns that only match import statements of one type but this will break down as soon as you have multiple import statements with the same import source but of different types, e.g.:

```js
import React from 'react';

import { useState } from 'react';
```

**Comment by gvNN7** [comment] 2021-08-30 23:43
Thanks a lot for your reply, it really clarify my question.
I also appreciate your attention on this "issue", your package is actually the closest i've reached to achieve the desired result, but actually, it gonna break if there some use-case like from your example.

By the way, do you know some plugin that get closer to what i wanna accomplish?

**Comment by KyleMayes** [comment] 2021-08-31 21:40
I'm not aware of any other ESLint plugins that support this feature.

**Closed as completed** 2021-11-30 04:46 UTC
